# syntax=docker/dockerfile:1.8
FROM gcr.io/distroless/static:nonroot

COPY --chmod=0755 deploy/docker/artifacts/gateway-service /gateway-service

WORKDIR /app
COPY services/gateway/internal/web/templates /app/internal/web/templates

EXPOSE 8080
USER nonroot
ENTRYPOINT ["/gateway-service"]