# syntax=docker/dockerfile:1.8
FROM gcr.io/distroless/static:nonroot

COPY --chmod=0755 deploy/docker/artifacts/payment-service /payment-service

EXPOSE 50054
USER nonroot
ENTRYPOINT ["/payment-service"]