# syntax=docker/dockerfile:1.8
FROM gcr.io/distroless/static:nonroot

COPY --chmod=0755 deploy/docker/artifacts/notification-service /notification-service

USER nonroot
ENTRYPOINT ["/notification-service"]