apiVersion: v1
kind: Service
metadata:
  name: qubool-kallyanam-chat
  namespace: qubool-kallyanam
  labels:
    app.kubernetes.io/name: qubool-kallyanam-chat
    app.kubernetes.io/part-of: qubool-kallyanam
spec:
  selector:
    app.kubernetes.io/name: qubool-kallyanam-chat
  ports:
    - name: grpc
      port: 50071
      targetPort: 50071
  type: ClusterIP