apiVersion: v1
kind: Service
metadata:
  name: qubool-kallyanam-payment
  namespace: qubool-kallyanam
  labels:
    app.kubernetes.io/name: qubool-kallyanam-payment
    app.kubernetes.io/part-of: qubool-kallyanam
spec:
  selector:
    app.kubernetes.io/name: qubool-kallyanam-payment
  ports:
    - name: grpc
      port: 50081
      targetPort: 50081
  type: ClusterIP